//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 05:43:20 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.parlament.gov.rs/propisi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		xmlns = {
				@javax.xml.bind.annotation.XmlNs(prefix="", namespaceURI="http://www.w3.org/ns/rdfa#"),
				@javax.xml.bind.annotation.XmlNs(prefix="xs", namespaceURI="http://www.w3.org/2001/XMLSchema#"),
				@javax.xml.bind.annotation.XmlNs(prefix="pr", namespaceURI="http://www.parlament.gov.rs/propisi"),
				@javax.xml.bind.annotation.XmlNs(prefix="pred", namespaceURI="http://www.parlament.gov.rs/predicate/"),
			}
			
		)
package rs.townhall.entity.regulation;
