//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 05:33:54 PM CEST 
//


package rs.townhall.entity.amendment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.townhall.entity.amendment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.townhall.entity.amendment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link Propis }
     * 
     */
    public Propis createPropis() {
        return new Propis();
    }

    /**
     * Create an instance of {@link Propis.Deo }
     * 
     */
    public Propis.Deo createPropisDeo() {
        return new Propis.Deo();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj }
     * 
     */
    public Clan.Sadrzaj createClanSadrzaj() {
        return new Clan.Sadrzaj();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj.Stav }
     * 
     */
    public Clan.Sadrzaj.Stav createClanSadrzajStav() {
        return new Clan.Sadrzaj.Stav();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj.Stav.Tacka }
     * 
     */
    public Clan.Sadrzaj.Stav.Tacka createClanSadrzajStavTacka() {
        return new Clan.Sadrzaj.Stav.Tacka();
    }

    /**
     * Create an instance of {@link Amandman.NazivPredloga }
     * 
     */
    public Amandman.NazivPredloga createAmandmanNazivPredloga() {
        return new Amandman.NazivPredloga();
    }

    /**
     * Create an instance of {@link Amandman.OdredbaPredloga }
     * 
     */
    public Amandman.OdredbaPredloga createAmandmanOdredbaPredloga() {
        return new Amandman.OdredbaPredloga();
    }

    /**
     * Create an instance of {@link Amandman.PredlozenoResenje }
     * 
     */
    public Amandman.PredlozenoResenje createAmandmanPredlozenoResenje() {
        return new Amandman.PredlozenoResenje();
    }

    /**
     * Create an instance of {@link Amandman.Podnosilac }
     * 
     */
    public Amandman.Podnosilac createAmandmanPodnosilac() {
        return new Amandman.Podnosilac();
    }

    /**
     * Create an instance of {@link Amandman.DatumDonosenja }
     * 
     */
    public Amandman.DatumDonosenja createAmandmanDatumDonosenja() {
        return new Amandman.DatumDonosenja();
    }

    /**
     * Create an instance of {@link Amandman.BrojGlasovaZa }
     * 
     */
    public Amandman.BrojGlasovaZa createAmandmanBrojGlasovaZa() {
        return new Amandman.BrojGlasovaZa();
    }

    /**
     * Create an instance of {@link Amandman.Mesto }
     * 
     */
    public Amandman.Mesto createAmandmanMesto() {
        return new Amandman.Mesto();
    }

    /**
     * Create an instance of {@link Amandman.BrojGlasovaProtiv }
     * 
     */
    public Amandman.BrojGlasovaProtiv createAmandmanBrojGlasovaProtiv() {
        return new Amandman.BrojGlasovaProtiv();
    }

    /**
     * Create an instance of {@link Amandman.DatumKreiranja }
     * 
     */
    public Amandman.DatumKreiranja createAmandmanDatumKreiranja() {
        return new Amandman.DatumKreiranja();
    }

    /**
     * Create an instance of {@link Odeljak }
     * 
     */
    public Odeljak createOdeljak() {
        return new Odeljak();
    }

    /**
     * Create an instance of {@link Clan.Opis }
     * 
     */
    public Clan.Opis createClanOpis() {
        return new Clan.Opis();
    }

    /**
     * Create an instance of {@link Propis.Naziv }
     * 
     */
    public Propis.Naziv createPropisNaziv() {
        return new Propis.Naziv();
    }

    /**
     * Create an instance of {@link Propis.Mesto }
     * 
     */
    public Propis.Mesto createPropisMesto() {
        return new Propis.Mesto();
    }

    /**
     * Create an instance of {@link Propis.DatumDonosenja }
     * 
     */
    public Propis.DatumDonosenja createPropisDatumDonosenja() {
        return new Propis.DatumDonosenja();
    }

    /**
     * Create an instance of {@link Propis.Deo.Glava }
     * 
     */
    public Propis.Deo.Glava createPropisDeoGlava() {
        return new Propis.Deo.Glava();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj.Link }
     * 
     */
    public Clan.Sadrzaj.Link createClanSadrzajLink() {
        return new Clan.Sadrzaj.Link();
    }

    /**
     * Create an instance of {@link Clan.Sadrzaj.Stav.Tacka.Podtacka }
     * 
     */
    public Clan.Sadrzaj.Stav.Tacka.Podtacka createClanSadrzajStavTackaPodtacka() {
        return new Clan.Sadrzaj.Stav.Tacka.Podtacka();
    }

}
